#!/bin/bash

# Update system and install Apache + mod_ssl
sudo dnf update -y
sudo yum install -y httpd mod_ssl mariadb105

# Enable and start Apache
sudo systemctl enable --now httpd

# Add website content
echo "Hello this is my website" > /var/www/html/index.html

